#!/bin/bash

IMAGE_URL="https://cloud.debian.org/images/cloud/bullseye/latest/debian-11-genericcloud-amd64.qcow2"
IMAGE_NAME="debian-11-genericcloud-amd64.qcow2"
TEMPLATE_ID="9000"
STORAGE_NAME="local-zfs"

qm destroy $TEMPLATE_ID

apt install libguestfs-tools -y

rm /tmp/* && cd /tmp
wget $IMAGE_URL

# Customize image and install qemu-guest-agent
# Debian does not entirely rely on cloud-init for network configuration, it will generate
# a dhcp config for the primary interface as this is commonly used with cloud providers
# We dont want that behaviour so we have to manually create the file which will mask the autogenerated
# /run/network/interfaces.d/ens18 file

virt-customize -a $IMAGE_NAME --install qemu-guest-agent --install resolvconf --update --run-command 'echo "auto ens18" >> /etc/network/interfaces.d/ens18' --run-command 'echo "iface ens18 inet manual" >> /etc/network/interfaces.d/ens18'

qm create $TEMPLATE_ID --memory 1024 --net0 virtio,bridge=vmbr0 --name "debian11"
qm importdisk $TEMPLATE_ID $IMAGE_NAME $STORAGE_NAME
qm set $TEMPLATE_ID --scsihw virtio-scsi-pci --scsi0 $STORAGE_NAME:vm-$TEMPLATE_ID-disk-0
qm set $TEMPLATE_ID --ide2 $STORAGE_NAME:cloudinit
qm set $TEMPLATE_ID --boot c --bootdisk scsi0
qm set $TEMPLATE_ID --serial0 socket --vga serial0
qm template $TEMPLATE_ID

# Todo:
# Enable qemu-guest-agent
# Set IPv6 to SLAAC
